[KingTower]
OnStartingAction="WaitForKingTowerActivation"
SkinType="KingTower"

[PrincessTower]
SkinType="PrincessTower"

[KingTower_Battleground]
OnStartingAction="WaitForKingTowerActivation"
SkinType="KingTower"

[PrincessTower_Battleground]
SkinType="PrincessTower"

[KingTower_LowHP]
OnStartingAction="WaitForKingTowerActivation"
SkinType="KingTower"

[PrincessTower_LowHP]
SkinType="PrincessTower"

[KingTower_chess]
SkinType="KingTower"

[PrincessTower_chess]
SkinType="PrincessTower"

[KingTower_IgnoreBarrel]
OnStartingAction="WaitForKingTowerActivation"
SkinType="KingTower"

[PrincessTower_IgnoreBarrel]
SkinType="PrincessTower"

[Tesla]
HideBeforeFirstHit=true
DeployTimeChangesDeployAnim=true	

